- .github/pull_request_template.md
This PR adds a template to the project.
> NOJIRA: Add PR template to project

- histree-frontend/index.html
- histree-frontend/src/App.tsx
- histree-frontend/src/components/Flow.tsx
- histree-frontend/src/components/TreeNodeCard.scss
- histree-frontend/src/components/TreeNodeCard.tsx
- histree-frontend/src/index.scss
- histree-frontend/src/index.tsx
- histree-frontend/src/pages/TreePage.scss
Set up tree structure with hard-coded data passed into TreeNodeCard components, which represent the collapsed profiles of each family member.
Next steps:
- Fixing the layout of the nodes - dynamically generate and ensure that the connections remain clear.
- Load data into tree when Redux store is set up.
> His 19 basic tree repr

- histree-frontend/package-lock.json
- histree-frontend/package.json
- histree-frontend/src/components/Flow.tsx
- histree-frontend/src/components/general/DescriptorCard.scss
- histree-frontend/src/components/general/DescriptorCard.tsx
- histree-frontend/src/index.scss
- histree-frontend/src/pages/TreePage.tsx
JIRA Link: [HIS-18][(JIRA URL](https://histree.atlassian.net/browse/HIS-18?atlOrigin=eyJpIjoiMzg4ZDIyOWRmZmJjNDIyMWExNzlkNjI3NzM4MWEyOTkiLCJwIjoiaiJ9))
Adds a floating card view so that we can examine each person more specifically.
Further details will be added in a later ticket.
> His 18: Expanded info for each individual on the tree after clicking the node

- histree-frontend/src/components/Flow.tsx
- histree-frontend/src/components/general/DepthBox.scss
- histree-frontend/src/components/general/DepthBox.tsx
- histree-frontend/src/pages/TreePage.tsx
- histree-frontend/src/stores/base.ts
JIRA Link: [HIS-31](https://histree.atlassian.net/browse/HIS-31?atlOrigin=eyJpIjoiZDRkNmE2NTRkYjc5NGZkZWFiYmExMjllOTQ4OGQzOTIiLCJwIjoiaiJ9)
Add depth selection box for expanding tree.
> HIS-31: expandable tree

- histree-frontend/src/components/TreeNodeCard.tsx
- histree-frontend/src/components/general/DepthBox.scss
- histree-frontend/src/components/general/DepthBox.tsx
- histree-frontend/src/components/general/DescriptorCard.scss
- histree-frontend/src/components/general/DescriptorCard.tsx
- histree-frontend/src/components/general/SearchBar.tsx
- histree-frontend/src/models/index.ts
- histree-frontend/src/models/mock.ts
- histree-frontend/src/models/selected.ts
- histree-frontend/src/pages/TreePage.tsx
- histree-frontend/src/stores/base.ts
JIRA Link: [HIS-41](https://histree.atlassian.net/browse/HIS-41?atlOrigin=eyJpIjoiZjM2NTYzZmE0NjExNGUyNDg0YTE3NmE3NzdjOGNkNWMiLCJwIjoiaiJ9)
Added additional fields to the Selected interface to populate the card with info.
Format DescriptorCard to hold various content (attributes, description and links), and handle overflow.
Mock data temporarily used as a placeholder.
> His 41 populate cards

- histree_backend/.gitignore
- histree_backend/deploy.sh
- histree_backend/histree.py
- histree_backend/histree_query.py
JIRA Link: [HIS-44](https://histree.atlassian.net/browse/HIS-44?atlOrigin=eyJpIjoiNzAyYzBhN2VkNWUxNDdmYWJlOGMwMGVjOGM5NjI4NDIiLCJwIjoiaiJ9)
pre-processes the query string (name of person) so it matches the format required by Wikidata. Also adds alternate label names to disambiguate between search results.
> HIS-44: add query processing and disambiguation

- histree-frontend/src/components/Flow.tsx
- histree-frontend/src/components/TreeNode.scss
- histree-frontend/src/components/TreeNode.tsx
- histree-frontend/src/components/TreeNodeCard.scss
- histree-frontend/src/components/general/SearchBar.tsx
- histree-frontend/src/models/renderContent.ts
- histree-frontend/src/services/connections.ts
- histree-frontend/src/stores/base.ts
JIRA Link: [HIS-48](https://histree.atlassian.net/browse/HIS-48?atlOrigin=eyJpIjoiZGE3ZTA5YTFlOGE4NDNiYTljMjUwNmYzYjI5ODk4YTMiLCJwIjoiaiJ9)
This PR makes the following changes
- Custom node implementation
- Fix debounce for search bar
> HIS-48: Frontend minor refactoring

- histree-frontend/src/components/Flow.tsx
- histree-frontend/src/components/TreeNode.tsx
- histree-frontend/src/components/general/DescriptorCard.scss
- histree-frontend/src/components/general/DescriptorCard.tsx
- histree-frontend/src/models/graphInfo.ts
- histree-frontend/src/services/connections.ts
JIRA Link: [HIS-57](https://histree.atlassian.net/browse/HIS-57?atlOrigin=eyJpIjoiN2M0Zjg5NzE3ZjViNGFhMGJjMDQ3YTdmOTFjYjE2MDEiLCJwIjoiaiJ9)
Populate card media field with image urls. Fix description passed into card and capitalization of petal descriptions.
> HIS-57: populate card images, format petal display and description

- histree_backend/database/neo4j_test.py
- histree_backend/database/people_db.py
- histree_backend/database/run_db_tests.sh
JIRA Link: [HIS-55](https://histree.atlassian.net/jira/software/projects/HIS/boards/1?selectedIssue=HIS-55)
The function `common_ancestor()` has been implemented and tested. This function takes in IDs of two people and returns the closest common ancestor i.e. the ancestor which has the shortest path length between the two when following the `PARENT_OF` relation.
> His 55 common ancestor backend

- histree-frontend/src/components/general/DescriptorCard.tsx
NO JIRA
Quick fix - capitalise start of description
> NOJIRA: capitalise description

- histree-frontend/.eslintrc.cjs
- histree-frontend/src/components/Flow.tsx
- histree-frontend/src/components/TreeNode.tsx
- histree-frontend/src/components/general/ComparisonCard.scss
- histree-frontend/src/components/general/ComparisonCard.tsx
- histree-frontend/src/components/general/ComparisonToggle.scss
- histree-frontend/src/components/general/ComparisonToggle.tsx
- histree-frontend/src/components/general/SearchBar.scss
- histree-frontend/src/components/general/SearchBar.tsx
- histree-frontend/src/components/general/index.ts
- histree-frontend/src/models/compareInfo.ts
- histree-frontend/src/models/edgeInfo.ts
- histree-frontend/src/models/graphInfo.ts
- histree-frontend/src/models/index.ts
- histree-frontend/src/models/renderContent.ts
- histree-frontend/src/pages/TreePage.tsx
- histree-frontend/src/services/connections.ts
- histree-frontend/src/stores/base.ts
- histree-frontend/src/utils/utils.ts
JIRA Link: [HIS-61](https://histree.atlassian.net/browse/HIS-61?atlOrigin=eyJpIjoiYmRhNzEzOWE2NzMzNDBiOGIwOGZmNmJhZDQxN2Q4NzciLCJwIjoiaiJ9)
This PR adds comparison edge drawing
> HIS-61: Implement 2 node selection

- histree-frontend/src/components/TreeNode.tsx
JIRA Link: [HIS-65](https://histree.atlassian.net/browse/HIS-65?atlOrigin=eyJpIjoiY2I1YjFkY2IwNTRiNDZmMWIzYjhiMzlkNWM0MWYzMGYiLCJwIjoiaiJ9)
Fix yellow handler on initial loaded node with no parent/children
> HIS-65: fix single initial loaded node having indefinite yellow handle

- histree-frontend/src/components/TreeNode.tsx
- histree-frontend/src/components/comparison/ComparisonCard.scss
- histree-frontend/src/components/comparison/ComparisonCard.tsx
- histree-frontend/src/components/comparison/ComparisonFlow.tsx
- histree-frontend/src/components/general/SearchBar.tsx
- histree-frontend/src/models/renderContent.ts
- histree-frontend/src/services/connections.ts
- histree-frontend/src/stores/base.ts
JIRA Link: [HIS-64](https://histree.atlassian.net/browse/HIS-64?atlOrigin=eyJpIjoiMDY2OWQ5ZDdlYjk2NDBkNjllNTg3MDM0MmM5ZDg2ZDMiLCJwIjoiaiJ9)
Fetch relationship data from backend into comparison card display.
> HIS-64: fetch relationship of compared nodes from backend

- histree-frontend/.eslintrc.cjs
- histree-frontend/src/components/comparison/ComparisonCard.scss
- histree-frontend/src/components/comparison/ComparisonFlow.scss
- histree-frontend/src/components/comparison/ComparisonFlow.tsx
- histree-frontend/src/stores/base.ts
JIRA Link: [HIS-67](https://histree.atlassian.net/browse/HIS-67?atlOrigin=eyJpIjoiNDAyODA5M2ZiMzQ0NDNjZDlhNDMzMTU3OTFkYjIzM2IiLCJwIjoiaiJ9)
Fix previously resizeable card view for comparison which cut off the nodes on smaller screen.
> HIS-67: Fix comparison card and reset selected nodes on switch back

- histree_backend/data_retrieval/query/builder.py
- histree_backend/data_retrieval/wikitree/tree.py
- histree_backend/data_retrieval/wikitree_instance/familytree/stems.py
- histree_backend/database/cypher_runner.py
JIRA Link: [HIS-73](https://histree.atlassian.net/jira/software/projects/HIS/boards/1?selectedIssue=HIS-73)
Fix branching status update in DB and parsing with single quotes.
> His 73 fix inefficient tree generation

- histree-frontend/src/components/Flow.tsx
- histree-frontend/src/components/TreeNode.tsx
- histree-frontend/src/components/general/SearchBar.tsx
- histree-frontend/src/models/expandInfo.ts
- histree-frontend/src/services/connections.ts
- histree-frontend/src/stores/base.ts
- histree-frontend/src/utils/utils.ts
- histree-frontend/src/utils/viewport.ts
JIRA Link: [HIS-68](https://histree.atlassian.net/browse/HIS-68?atlOrigin=eyJpIjoiZjA2OWNiYjEwMDlmNGJjOGIzYjg2YzY3ZjY1Mjg1MDUiLCJwIjoiaiJ9)
Fix a couple of bugs
- Prevent search bar text from disappearing
- Prevent search suggestions from getting clobbered and disappearing
Implement movement rendering
> HIS-68: Implement movement rendering

- histree-frontend/src/components/general/SearchBar.tsx
- histree-frontend/src/utils/utils.ts
JIRA Link: [HIS-79](https://histree.atlassian.net/browse/HIS-79?atlOrigin=eyJpIjoiMGYxNGVmMTdmNmI1NDVjMWEyNDBiNGUwOThjN2RiZjAiLCJwIjoiaiJ9)
Add descriptions to searchbar
> HIS-79: Add description to ausearchbar suggestion options

- histree-frontend/src/components/Flow.tsx
- histree-frontend/src/components/TreeNode.tsx
- histree-frontend/src/components/comparison/ComparisonCard.scss
- histree-frontend/src/components/comparison/ComparisonCard.tsx
- histree-frontend/src/components/comparison/ComparisonToggle.scss
- histree-frontend/src/components/general/SearchBar.scss
- histree-frontend/src/pages/TreePage.scss
- histree-frontend/src/pages/TreePage.tsx
JIRA Link: [HIS-80](https://histree.atlassian.net/browse/HIS-80?atlOrigin=eyJpIjoiNGIyY2NlNWNmNTVjNDk0NzhhMmE1OTEwNTQ5ZWRkNDgiLCJwIjoiaiJ9)
Fix infinite refetching bug on comparison node
> HIS-80: Fix infinite fetching bug

- histree-frontend/src/components/Flow.tsx
- histree-frontend/src/components/TreeEdge.tsx
- histree-frontend/src/components/TreeNode.tsx
- histree-frontend/src/components/general/SearchBar.tsx
- histree-frontend/src/stores/base.ts
- histree-frontend/src/utils/utils.ts
JIRA Link: [HIS-81](https://histree.atlassian.net/browse/HIS-81?atlOrigin=eyJpIjoiNDI1ZGJjZWQyYmMyNGNjNjgwNTQxNDk3MGNiOTFkY2IiLCJwIjoiaiJ9)
Change our current edges to a custom edge
> HIS-81: custom edge

- histree-frontend/src/components/general/CenterSearched.scss
- histree-frontend/src/components/general/CenterSearched.tsx
- histree-frontend/src/components/general/SearchBar.tsx
- histree-frontend/src/pages/TreePage.tsx
JIRA Link: [HIS-78](https://histree.atlassian.net/browse/HIS-78?atlOrigin=eyJpIjoiZGRiMmUxOWEwYTZlNGU3ZmI5NGY1NjFlZjM4YWNlY2IiLCJwIjoiaiJ9)
Add center on search button
> HIS-78: center on search button implementation

- histree-frontend/package-lock.json
- histree-frontend/package.json
- histree-frontend/src/components/general/SearchBar.tsx
JIRA Link: [HIS-82](https://histree.atlassian.net/browse/HIS-82?atlOrigin=eyJpIjoiNmJlZDRmM2Y1YWNmNDZhMDhhMTZkMzM5NDMwMTJiYmQiLCJwIjoiaiJ9)
<Your PR's description goes here.>
> HIS-82: Fix search on enter bug

- histree_backend/data_retrieval/wikitree/flower.py
- histree_backend/data_retrieval/wikitree/tree.py
- histree_backend/database/cypher_runner.py
JIRA Link: [HIS-77](https://histree.atlassian.net/browse/HIS-77?atlOrigin=eyJpIjoiN2FlMmQzYzMwMTE1NDJiOWJjNmNhZjZiMzFmZjVhZGUiLCJwIjoiaiJ9)
- flattened location data in JSON format
- remove print statement when merging to database
> His 77 location petals (follow up)

- histree_backend/data_retrieval/query/builder.py
- histree_backend/data_retrieval/query/parser.py
- histree_backend/data_retrieval/wikitree/flower.py
- histree_backend/data_retrieval/wikitree/tree.py
JIRA Link: [HIS-77](https://histree.atlassian.net/browse/HIS-77?atlOrigin=eyJpIjoiNWUwZGUwNWYyNDk1NGQ2YmFlZTliYTM5NTQxMmFlZTUiLCJwIjoiaiJ9)
- add Wikipedia article to each entity
- catch server error when locations are unknown
> His 77 location petals (follow follow up)

- histree-frontend/src/components/Flow.tsx
- histree-frontend/src/components/TreeEdge.tsx
- histree-frontend/src/components/TreeNode.tsx
- histree-frontend/src/components/childrenFinder/ChildrenFinderCard.scss
- histree-frontend/src/components/childrenFinder/ChildrenFinderCard.tsx
- histree-frontend/src/components/childrenFinder/ChildrenFinderFlow.scss
- histree-frontend/src/components/childrenFinder/ChildrenFinderFlow.tsx
- histree-frontend/src/components/childrenFinder/index.ts
- histree-frontend/src/components/comparison/ModeIcons.scss
- histree-frontend/src/components/comparison/ModeIcons.tsx
- histree-frontend/src/components/general/SearchBar.tsx
- histree-frontend/src/components/index.ts
- histree-frontend/src/models/renderContent.ts
- histree-frontend/src/pages/TreePage.tsx
- histree-frontend/src/services/connections.ts
- histree-frontend/src/stores/base.ts
- histree-frontend/src/utils/utils.ts
JIRA Link: [HIS-84](https://histree.atlassian.net/browse/HIS-84?atlOrigin=eyJpIjoiYzc5MjBkMDRhZTYyNDk5ZDlhZTE4NDE4ZmFmY2ExNzgiLCJwIjoiaiJ9)
> HIS-84: Fix name disappearing on mode switch

- histree-frontend/src/components/TreeNode.tsx
JIRA Link: [HIS-92](https://histree.atlassian.net/browse/HIS-92?atlOrigin=eyJpIjoiMmU3OTgzODgxM2IxNGI3Yzg0YjIyOGNjOTdjYTQxZTEiLCJwIjoiaiJ9)
All around me are familiar faces
Worn out places, worn out faces
Bright and early for the daily races
Going nowhere, going nowhere
Their tears are filling up their glasses
No expression, no expression
Hide my head, I wanna drown my sorrow
No tomorrow, no tomorrow
And I find it kind of funny
I find it kind of sad
The dreams in which I'm dying
Are the best I've ever had
I find it hard to tell you
I find it hard to take
When people run in circles it's a very, very
Mad world, mad world
Children waiting for the day they feel good
Happy birthday, happy birthday
And I feel the way that every child should
Sit and listen, sit and listen
Went to school and I …
> HIS-92: Disable movement rendering

- histree-frontend/src/components/childrenFinder/ChildrenFinderCard.tsx
- histree-frontend/src/components/comparison/ComparisonCard.tsx
- histree-frontend/src/components/filter/FilterCard.tsx
JIRA Link: [HIS-96](https://histree.atlassian.net/browse/HIS-96?atlOrigin=eyJpIjoiYmNjMDliMGE4MWI4NDgzODk5NjEzYTJhZDRmMGQwNTciLCJwIjoiaiJ9)
Filtering no longer enabled before search term has loaded in.
Also changed fonts on all top left cards to match.
> HIS-96: hide filters before searched content is rendered

- histree-frontend/src/components/help/FrontPageHelp.tsx
- histree-frontend/src/components/help/HelpInformation.tsx
- histree-frontend/src/pages/TreePage.tsx
JIRA Link: [HIS-100](https://histree.atlassian.net/browse/HIS-100?atlOrigin=eyJpIjoiOGNmMTAyYTFhYzFkNDcxYmIyNGEzNzNjYzM0ZDI4NzUiLCJwIjoiaiJ9)
Filtering information now in help info.
Small changes to help info for formatting and clearer navigation instructions.
> HIS-100: add filtering directions and format help information

- histree-frontend/src/components/Flow.tsx
- histree-frontend/src/utils/utils.ts
JIRA Link: [HIS-105](https://histree.atlassian.net/browse/HIS-105?atlOrigin=eyJpIjoiMjA3M2VjNTJhZDUxNDMyZWE1ZmNlMGI0OTZmNGEzMDciLCJwIjoiaiJ9)
<Your PR's description goes here.>
> HIS-105: change spouse line on selection expansion

- histree-frontend/src/components/TreeNode.tsx
- histree-frontend/src/components/filter/FilterCard.scss
- histree-frontend/src/components/filter/FilterCard.tsx
- histree-frontend/src/components/filter/FilterDateRange.tsx
- histree-frontend/src/components/filter/FilterSwitch.tsx
- histree-frontend/src/components/filter/FilterText.tsx
- histree-frontend/src/components/filter/FilterToggle.tsx
- histree-frontend/src/components/general/DescriptorCard.tsx
- histree-frontend/src/models/filterInfo.ts
- histree-frontend/src/stores/base.ts
- histree-frontend/src/utils/filter.ts
JIRA Link: [HIS-95](https://histree.atlassian.net/browse/HIS-95?atlOrigin=eyJpIjoiOGViMWIzMWI0YTU5NDYzYmE4MmI4M2MwNzE3NzFhNzYiLCJwIjoiaiJ9)
Created components for different types of filters: date range, text, switch (on/off), and toggle (multiple choice)
Added filters for: died between, contains search term, marriage status.
> Added filters and toggles to FilterCard

- histree-frontend/index.html
JIRA Link: [HIS-109](https://histree.atlassian.net/browse/HIS-109?atlOrigin=eyJpIjoiODM3YzRmYmFmNzcwNDk4ZGE2ZTMyOWFkY2E0ZDM2YzYiLCJwIjoiaiJ9)
Removed 'loading' text from the default index page.
> HIS-109: removed loading from default index.html

- histree-frontend/src/components/TreeNode.tsx
- histree-frontend/src/components/filter/FilterCard.tsx
JIRA Link: [HIS-111](https://histree.atlassian.net/browse/HIS-111?atlOrigin=eyJpIjoiMGRkNTI3ZGU1NDA2NDhjOGFkNmUyNTRiMTZlMzdmYTEiLCJwIjoiaiJ9)
<Your PR's description goes here.>
> HIS-111: Add search highlight

- histree-frontend/src/components/general/DescriptorCard.tsx
<Your PR's description goes here.>
> NOJIRA: Remove learn more button for people with no article links
